project: bbo_bench_example
method: grid
metric:
  goal: minimize
  name: black_box/cumulative_regret

parameters:
  exp_name:
    value: llome_lambo_reproduction
  random_seed:
    value: 0
  test_function:
    values:
      - ehr_v-08_l-128_m-8_c-8_q-8
      - ehr_v-32_l-032_m-4_c-4_q-2
      - ehr_v-32_l-032_m-4_c-4_q-4
      - ehr_v-32_l-128_m-4_c-4_q-2
      - ehr_v-32_l-128_m-4_c-4_q-4
      - ehr_v-32_l-128_m-8_c-8_q-8
  num_opt_steps:
    value: 12
  run_presolver:
    value: False

  # Optimizer Parameters
  optimizer.batch_size:
    value: 128
  optimizer.num_samples:
    value: 2000
  optimizer.num_steps:
    value: 64
  optimizer.num_mutations_per_step:
    values: [16, 24]
  optimizer.max_epochs:
    value: 16
  optimizer.fft_expansion_factor:
    value: 2
  optimizer.optim.max_guidance_updates:
    value: 2
  optimizer.optim.guidance_step_size:
    values: [0.01, 0.05]
  optimizer.optim.kl_weight:
    value: 0
  optimizer.optim.exclude_initial_solution:
    value: False


program: scripts/benchmark_optimizer.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
