_target_: poli.objective_repository.EhrlichHoloBlackBox
sequence_length: 128
n_motifs: 8
motif_length: 8
quantization: ${test_function.motif_length}
epistasis_factor: 0.0
noise_std: 0.0
alphabet:  ["A", "R", "N", "D", "C", "E", "Q", "G"] # vocab of size 8
seed: 50494 # only change this if you want to change the actual test function instance
