protein_seq:
  _target_: cortex.model.root.Conv1dRoot
  corruption_process:
    _target_: cortex.corruption.MaskCorruptionProcess
    t_base_dist:
      _target_: torch.distributions.Beta
      concentration1: 3
      concentration0: 1
  tokenizer_transform:
    _target_: cortex.transforms.HuggingFaceTokenizerTransform
    tokenizer:
      _target_: cortex.tokenization.ProteinSequenceTokenizerFast
      vocab_file: null
  max_len: ${optimizer.max_sequence_length}
  embed_dim: ${optimizer.embed_dim}
  channel_dim: ${optimizer.feature_dim}
  out_dim: ${optimizer.embed_dim}
  num_blocks: 2
  kernel_size: ${optimizer.kernel_size}
